apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-statsd-v1-service"
  labels:
    app: "{{ .Release.Name }}-statsd-v1"
spec:
  selector:
    app: '{{ template "metricbeat.fullname" . }}-metrics'
  ports:
  - name: statsd-udp-port
    protocol: UDP
    port: 8125
  - name: statsd-tcp-port
    protocol: TCP
    port: 8125
