apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-statsd-v1-service"
  labels:
    app: statsd-v1
spec:
  selector:
    app: '{{ template "metricbeat.fullname" . }}-metrics'
  ports:
  - protocol: UDP
    port: 8125
